import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import type {CSSProperties, PropsWithChildren} from "react";
import {Suspense} from "react";
import {ClientProviders} from "~/components/providers";
import {AppSidebar} from "~/components/sidebar";
import SiteHeader from "~/components/sidebar/SiteHeader";
import {SidebarInset, SidebarProvider} from "~/components/ui/sidebar";
import NewEventDialog from "~/components/NewEventDialog";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const style: CSSProperties = {
    "--sidebar-width": "calc(var(--spacing) * 72)",
    "--header-height": "calc(var(--spacing) * 12)",
} as CSSProperties;

export default async function RootLayout({children}: PropsWithChildren) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Suspense fallback={<div className="min-h-screen bg-background"/>}>
            <ClientProviders>
                <SidebarProvider style={style} defaultOpen={false}>
                    <AppSidebar variant="inset"/>
                    <SidebarInset>
                        <SiteHeader/>
                        {children}
                        <NewEventDialog />
                    </SidebarInset>
                </SidebarProvider>
            </ClientProviders>
        </Suspense>
        </body>
        </html>
    );
}
