/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
import type { JSONObject, Simplify } from "~/domain/utils-types";

export type DrizzleMigration = {
  createdAt?: string | null;
  hash: string;
  id?: string;
};
export type Account = {
  accessToken?: string | null;
  accessTokenExpiresAt?: Date | null;
  accountId: string;
  createdAt?: Date;
  id: string;
  idToken?: string | null;
  password?: string | null;
  providerId: string;
  refreshToken?: string | null;
  refreshTokenExpiresAt?: Date | null;
  scope?: string | null;
  updatedAt?: Date;
  userId: string;
};
export type AuditLog = {
  action: string;
  actorId?: string | null;
  actorType: string;
  createdAt?: Date;
  entityId?: string | null;
  entityType: string;
  id: string;
  metadata?: string | null;
  payload?: JSONObject | null;
  source: string;
  teamSlug: string;
};
export type EventRule = {
  createdAt?: Date | null | undefined;
  description?: string | null | undefined;
  editAccess?: string;
  enabled?: boolean | null | undefined;
  errorMessage: string;
  eventId: string;
  id: string;
  name: string;
  query?: string | null | undefined;
  updatedAt?: Date | null | undefined;
};
export type Event = {
  createdById?: string | null | undefined;
  editAccess?: string;
  eventSchema?: JSONObject | null | undefined;
  icon: string;
  id: string;
  label: string;
  teamId: string;
  type: string;
  updatedAt?: Date | null | undefined;
};

export type Member = {
  createdAt?: Date | null | undefined;
  id: string;
  organizationId: string;
  role?: string;
  userId: string;
};

export type RewardRuleQueryItem = {
  query: string;
  errorMessage: string;
  description?: string;
};

export type RewardRule = {
  column?: string | null | undefined;
  createdAt?: Date | null | undefined;
  editAccess?: string;
  enabled?: boolean | null | undefined;
  eventId: string;
  id: string;
  name: string;
  queries?: RewardRuleQueryItem[] | null | undefined;
  tab?: string | null | undefined;
  updatedAt?: Date | null | undefined;
};

export type EventWithRules = Simplify<
  Event & {
    eventRules?: EventRule[] | null | undefined;
    rewardRules?: RewardRule[] | null | undefined;
  }
>;
export type DbSession = {
  activeOrganizationId?: string | null;
  activeTeamId?: string | null;
  createdAt?: Date;
  expiresAt: Date;
  id: string;
  impersonatedBy?: string | null;
  ipAddress?: string | null;
  token: string;
  updatedAt?: Date;
  userAgent?: string | null;
  userId: string;
};
export type TeamMember = {
  createdAt?: Date;
  id: string;
  role?: string;
  teamId: string;
  userId: string;
};
export type Team = {
  createdAt?: Date;
  id: string;
  name: string;
  organizationId: string;
  slug: string;
  updatedAt?: Date;
};
export type User = {
  banExpires?: Date | null;
  banReason?: string | null;
  banned?: any | null;
  createdAt?: Date;
  email: string;
  emailVerified?: any;
  id: string;
  image?: string | null;
  name: string;
  role?: string | null;
  updatedAt?: Date;
};
export type Verification = {
  createdAt?: Date;
  expiresAt: Date;
  id: string;
  identifier: string;
  updatedAt?: Date;
  value: string;
};

export type Organization = {
  id: string;
  name: string;
  slug: string;
  logo?: string | null | undefined;
  metadata?: JSONObject | null | undefined;
  createdAt?: Date | null | undefined;
};

export type Invitation = {
  createdAt?: Date;
  email: string;
  expiresAt: Date;
  id: string;
  inviterId: string;
  organizationId: string;
  role?: string | null;
  status?: string;
  teamId?: string | null;
};

export type Membership = Member & {
  user: User;
};

export type FullOrganization = Simplify<
  Organization & {
    teams?: Team[] | null | undefined;
    members?: Membership[] | null | undefined;
    invitations?: Invitation[] | null | undefined;
  }
>;
